
language: objective-c
osx_image: xcode9.2

env:
  global:
    # CC_TEST_REPORTER_ID=

before_script:
  #- gem install slather
  #- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  #- chmod +x ./cc-test-reporter

script:
  - xcodebuild -sdk iphonesimulator -project XibViewKit.xcodeproj -scheme XibViewKit -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2' CODE_SIGNING_REQUIRED=NO clean test

after_script:
  #- slather coverage -x --travis --scheme XibViewKit XibViewKit.xcodeproj
  #- ./cc-test-reporter format-coverage -t cobertura
  #- if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
  